# Generated by Django 2.0.6 on 2018-06-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pw', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('credit', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
